version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - symfony_net

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab
      MYSQL_USER: lab
      MYSQL_PASSWORD: lab
    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge

volumes:
  db_data:
    driver: local
